<?php
    function groceries_menu() {
        $items = array();
        $items['groceries_list'] = array(
            'title' => 'Groceries',
            'page callback' => 'groceries_callback',
            'access callback' => TRUE,
            'type' => MENU_NORMAL_ITEM,
        );
        return $items;
    }



    function groceries_callback() {
        $my_groceries['eggs'] = array(
            'name' => 'eggs',
            'price' => 1.99,
            'quantity' => 3,
        );
        $my_groceries['chocolate'] = array(
            'name' => 'chocolate',
            'price' => 4.99,
            'quantity' => 1
        );
        $my_groceries['coffee'] = array(
            'name' => 'coffee',
            'price' => 10.99,
            'quantity' => 1
        );
        $my_groceries['cheese'] = array(
            'name' => 'cheese',
            'price' => 7.99,
            'quantity' => 2
        );
        $my_groceries['bread'] = array(
            'name' => 'bread',
            'price' => 2.99,
            'quantity' => 2
        );

        $output = "";
        $total = 0;
        foreach($my_groceries as $key => $value) {
            $total = $total + $value['price'] * $value['quantity'];
            $output .= ("<p>" . $value['quantity'] . " " . $value['name'] . " - " . "$" . $value['price'] . "</p>");
            $output .= 'Total: ' . "$" . $total;

        }
        return $output;


    }
