<?php

function hello_user_menu() {
    $items = array();
    $items['hello_user'] = array(
        'title' => 'Hello User',
        'page callback' => 'greet_user',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function greet_user() {
    return "<p>Welcome to party pal :)</p>";
}

function hello_user_user_insert() {
    $_GET['destination'] = 'hello_user';
  }
