<?php

 function greeting_menu() {
    $items = array();
    $items['hello_friend'] = array(
        'title' => "Hello Friend!",
        'page callback' => 'say_hello',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    $items['farewell'] = array(
        'title' => 'Farewell Friend',
        'page callback' => 'say_farewell',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
 }

 function say_hello() {
     $user = ($GLOBALS['user']);

     if ((($user->roles[2]) == 'authenticated user') && ($user->roles[3]) == 'administrator') {//is the user an admin and authenticated user?
        return 'Weclome Admin Master Overlord';
    } elseif ((($user->roles[2]) == 'authenticated user')) {//is the user an authenticated user?
        return "Welcome Puny Authenticated User Baby";
    } else {// does not work?
        return "puny peasant anonymous user! Register for an account";
    }
 }

 function say_farewell() {
     $user = ($GLOBALS['user']);
     var_dump($user);
     if ((($user->roles[2]) == 'authenticated user') && ($user->roles[3]) == 'administrator') {
        return 'Goodbye Admin Master Overlord';
    } else {
        return "farewell";
    }
 }

 function greeting_user_login() {
     $_GET['destination'] = 'hello_friend';
 }

 function greeting_user_logout() {
     $_GET['destination'] = 'farewell';
 }
